# Default profile
spring.profiles.active=production

# Config
spring.application.name=figuras_ocultas
spring.jpa.open-in-view=false
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.jpa.hibernate.ddl-auto=update