spring.datasource.url=jdbc:mysql://mysql-sav-gamificacion.cngo8a0wizra.eu-north-1.rds.amazonaws.com:3306/figuras_ocultas
spring.datasource.username=root
spring.datasource.password=root1234
server.port=8080
