name: Auto Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Desplegar en Raspberry Pi via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.RASPBERRY_HOST }}
          username: ${{ secrets.RASPBERRY_USER }}
          key: ${{ secrets.RASPBERRY_SSH_KEY }}
          script: |
            cd ${{ secrets.RASPBERRY_PROJECT_DIR }}
            bash deploy.sh